version: '3.8'

services:

  traefik:
    image: "traefik:v2.5"
    container_name: traefik
    command:
      # - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=califesstyler@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`kryptonews.fun`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.middlewares=api-strip,auth_dashboard"
      - "traefik.http.middlewares.auth_dashboard.basicauth.users=admin:$$apr1$$3um6k7fh$$s383PcsEIzs9fqbV.vANu0"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/dashboard"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.services.api.loadbalancer.server.port=8080"

    ports:
      - "80:80"
      - "443:443"
      - "8084:8080"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

  db:
    image: mariadb
    container_name: mariadb
    env_file:
      - .env.mariadb
    labels:
      - "traefik.enable=false" # Ne pas exposer MariaDB via Traefik
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - back-db
      - traefik

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin
    env_file:
      - .env.phpmyadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`kryptonews.fun`) && PathPrefix(`/phpmyadmin`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=myresolver"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.phpmyadmin.middlewares=phpmyadmin-strip,auth_phpmyadmin"
      - "traefik.http.middlewares.auth_phpmyadmin.basicauth.users=krypto:$$apr1$$58zkdbvu$$Cpl91xhXhkly3Y/f/Si2L1"
      - "traefik.http.middlewares.phpmyadmin-strip.stripprefix.prefixes=/phpmyadmin"
    depends_on:
      - db
      - traefik
    ports:
      - "8081:80"
    networks:
      - back-db
      - traefik

  back:
    image: kryptonews/express_server
    container_name: express_server
    env_file:
      - .env.back
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.back.rule=Host(`kryptonews.fun`) && PathPrefix(`/back`)"
      - "traefik.http.routers.back.entrypoints=websecure"
      - "traefik.http.routers.back.tls=true"
      - "traefik.http.routers.back.tls.certresolver=myresolver"
      - "traefik.http.services.back.loadbalancer.server.port=8080"
      - "traefik.http.routers.back.middlewares=back-strip"
      - "traefik.http.middlewares.back-strip.stripprefix.prefixes=/back"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - traefik
    command: [ "npm", "start" ]
    networks:
      - back-db
      - traefik

  front:
    image: kryptonews/react_app
    container_name: react_app
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.front-http.entrypoints=web"
      # - "traefik.http.routers.front-http.rule=Host(`kryptonews.store`) && PathPrefix(`/`)"
      # - "traefik.http.routers.front-http.middlewares=front-https"
      # - "traefik.http.middlewares.front-https.redirectscheme.scheme=https"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.rule=Host(`kryptonews.fun`) && PathPrefix(`/`)"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=myresolver"
      - "traefik.http.services.front.loadbalancer.server.port=80"
      # - "traefik.http.routers.front.middlewares=front-strip"
      # - "traefik.http.middlewares.front-strip.stripprefix.prefixes=/front"
      # - "traefik.http.middlewares.front-redirectscheme.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.front-redirectscheme.redirectscheme.permanent=true"
    depends_on:
      - back
      - traefik
    networks:
      - traefik

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    labels:
      - "traefik.enable=false"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - back-db
      - front-back
      - traefik

volumes:
  mariadb_data:
  portainer_data:


networks:
  back-db:
  front-back:
  traefik:
